"""
Merge helper - turns the 4 team files into one standalone quiz_app_single.py

Run it after everybody's part is committed:

    python build_single_file.py

What it does (exactly what you would do by hand, just without typos):
  1. reads the 4 files in dependency order
  2. deletes the cross-file imports (from questions import ...) - not needed
     once everything is in one file
  3. hoists every standard-library import to the top and removes duplicates
  4. drops each file's `if __name__ == "__main__":` self-test block, keeping
     only the one from main.py
  5. writes the result with a banner comment between each part
"""

import ast
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "quiz_app_single.py"

# Order matters: definitions must appear before the code that uses them.
PARTS = [
    ("questions.py", "PART 1 of 4 - QUESTION BANK", "Person 1"),
    ("quiz_logic.py", "PART 2 of 4 - QUIZ ENGINE", "Person 2"),
    ("scoreboard.py", "PART 3 of 4 - SCOREBOARD & REPORTS", "Person 3"),
    ("main.py", "PART 4 of 4 - MENUS & INPUT", "Person 4"),
]

LOCAL_MODULES = {"questions", "quiz_logic", "scoreboard", "main"}

HEADER = '''"""
Quiz App - single-file build
============================
Auto-generated by build_single_file.py - do NOT edit this file by hand.
Edit questions.py / quiz_logic.py / scoreboard.py / main.py and rebuild.

Run with:  python quiz_app_single.py
"""
'''


def is_main_guard(node) -> bool:
    """True for `if __name__ == "__main__":`"""
    if not isinstance(node, ast.If):
        return False
    test = node.test
    return (
        isinstance(test, ast.Compare)
        and isinstance(test.left, ast.Name)
        and test.left.id == "__name__"
    )


def import_key(node):
    """
    Describe one import so duplicates across files collapse:
      import json            -> ("plain", "json",   ["json"])
      from typing import Any -> ("from",  "typing", ["Any"])
    """
    if isinstance(node, ast.Import):
        names = [a.name + (f" as {a.asname}" if a.asname else "") for a in node.names]
        return ("plain", "", names)
    names = [a.name + (f" as {a.asname}" if a.asname else "") for a in node.names]
    return ("from", node.module or "", names)


def render_imports(collected) -> str:
    """Turn the collected imports into a tidy, de-duplicated import block."""
    plain, from_modules = set(), {}

    for kind, module, names in collected:
        if kind == "plain":
            plain.update(names)
        else:
            from_modules.setdefault(module, set()).update(names)

    lines = [f"import {name}" for name in sorted(plain)]
    for module in sorted(from_modules):
        names = ", ".join(sorted(from_modules[module]))
        lines.append(f"from {module} import {names}")
    return "\n".join(lines)


def split_module(path: Path, keep_main_guard: bool):
    """Return (imports, body_text) for one part."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    lines = source.splitlines()

    drop = set()          # 0-based line numbers to remove from the body
    imports = []

    for i, node in enumerate(tree.body):
        span = range(node.lineno - 1, node.end_lineno)

        # the module docstring - replaced by our banner comment
        is_docstring = (
            i == 0
            and isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        )
        if is_docstring:
            drop.update(span)
            continue

        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if isinstance(node, ast.ImportFrom):
                local = (node.module or "").split(".")[0] in LOCAL_MODULES
            else:
                local = any(a.name.split(".")[0] in LOCAL_MODULES for a in node.names)
            if not local:
                imports.append(import_key(node))
            drop.update(span)
            continue

        if is_main_guard(node) and not keep_main_guard:
            drop.update(span)

    body = "\n".join(line for n, line in enumerate(lines) if n not in drop)
    return imports, body.strip("\n")


def build() -> Path:
    all_imports = []
    chunks = []

    for filename, title, owner in PARTS:
        path = HERE / filename
        if not path.exists():
            raise SystemExit(f"Missing {filename} - is everyone's part in this folder?")

        keep_main = filename == "main.py"
        imports, body = split_module(path, keep_main_guard=keep_main)
        all_imports.extend(imports)

        banner = (
            "# " + "=" * 74 + "\n"
            f"# {title}   (originally {filename}, by {owner})\n"
            "# " + "=" * 74
        )
        chunks.append(f"{banner}\n\n{body}\n")

    OUTPUT.write_text(
        HEADER + "\n" + render_imports(all_imports) + "\n\n\n" + "\n\n".join(chunks),
        encoding="utf-8",
    )
    return OUTPUT


if __name__ == "__main__":
    out = build()
    line_count = len(out.read_text(encoding="utf-8").splitlines())
    print(f"Built {out.name} ({line_count} lines) from {len(PARTS)} files.")
    print("Test it with:  python quiz_app_single.py")
